#pragma once

#define ERROR_GLEW_INIT_FAIL 			"GLEW::INITIALIZATION_FAILED"
#define ERROR_FREETYPE_INIT_FAIL		"FREETYPE::INITIALIZATION_FAILED"

#define ERROR_SHADER_COMPILE_VERTEX 	"SHADER::VERTEX::COMPILATION_FAILED"
#define ERROR_SHADER_COMPILE_FRAGMENT 	"SHADER::FRAGMENT::COMPILATION_FAILED"
